apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-bff
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobile-bff
  template:
    metadata:
      labels:
        app: mobile-bff
    spec:
      containers:
        - name: mobile-bff
          image: d1zzy0316/mobile-bff:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: BOOK_SERVICE_URL
              value: "http://book-service:8001"
            - name: CUSTOMER_SERVICE_URL
              value: "http://customer-service:8002"
          livenessProbe:
            httpGet:
              path: /status
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3